### ISSUE TITLE
Is hqmf1.xml retired?

### ISSUE THREAD

**Issue by papsofts** [MeasureAuthoringTool/health-data-standards#334]
Hi ,

Would like to know if hqmf1.xml is retired in health-data-standards version 3.6.1?
My code is referring to template Ids for data_criterias mentioned in hqmf1.xml of version 2.4.0.
Should I be replacing all my old templateIds of all data_criteria to refer to hqmf2.xml's templateIds from 3.6.1 version?

**Comment by pkmitre** [comment]
The HQMF R1 functionality is still supported, and maintained separately from HQMF R2 support. Which template IDs to use will depend on which standard you want to support.
