### ISSUE TITLE
How to pass in "codes" when parsing HQMF R1 files

### ISSUE THREAD

**Issue by marks** [MeasureAuthoringTool/health-data-standards#41]
I get the following messages when parsing a HQMF R1 file, for example [CMS60v2.xml ](view-source:https://ushik.ahrq.gov/rest/meaningfulUse/retrieveHQMFXML?MeasureId=60&format=hqmf&version=2) (from USHIK/CMS):
- Codes not passed in, cannot backfill properties like gender
- no code set to back fill: Clinical Trial Participant
- no code set to back fill: Clinical Trial Participant
- no code set to back fill: Clinical Trial Participant
- no code set to back fill: birth date
- no code set to back fill: birth date
- no code set to back fill: Clinical Trial Participant
- no code set to back fill: Clinical Trial Participant
- (0164)codes are nil!!!!!!!!!!!

I have traced these messages back to https://github.com/projectcypress/health-data-standards/blob/7896e22444f8ff51f5c5dbca4c12cb5be7c03e11/lib/hqmf-parser/converter/pass1/document_converter.rb and https://github.com/projectcypress/health-data-standards/blob/7896e22444f8ff51f5c5dbca4c12cb5be7c03e11/lib/hqmf-parser/parser.rb

**Are "codes" another name for value sets/concepts? Is there an example of how to parse HQMF R1 with this library while providing "codes"?**

Thanks in advance!

**Comment by andrequina** [comment]
We typically load measures through the Bonnie project.  That has the
wrappers to pull value set oids from the HQMF and load the value sets from
VSAC.  Ideally, HQMF Parser would be standalone, but as things evolved from
having Value Sets  in XLS files to values sets from the VSAC service we
were not able to keep up with maintaining the independence of HQMF parser
as a standalone utility.

If you look at the rake task:

bonnie:initialize

in:

https://github.com/pophealth/bonnie/blob/master/lib/tasks/bonnie.rake

That should do the work of pulling the value sets from HQMF and loading
them from VSAC then parsing and loading the measures.  Ideally some of
these rake tasks would be migrated back into health data standards, but
there would be some cleanup that would need to be done around these before
they could be merged into HDS.

**Comment by marks** [comment]
Thank you for pointing me toward Bonnie for how codes are passed..  I've tracked the functionality to https://github.com/pophealth/bonnie/blob/master/lib/tasks/measures.rake and then https://github.com/pophealth/bonnie/blob/master/lib/measures/loader.rb#L157 and think I mostly understand what that code does to pass VS OIDs in.

**What exactly does passing the codes in do though?** Some context: for the work I am doing, we are ingesting parsed HQMF for measure and data-element level analysis? We, too, are getting Value Sets from VSAC and linking them to each measure by the measures' data element `code_list_id` and `negation_code_list_id`s. Is that what passing the code IDs into the HQMF parser/converter does in HDS (and Bonnie, which uses HDS) or what?

Thanks again for the quick reply, @andrequina!

**Comment by andrequina** [comment]
It mostly is used for embedding the value for gender into the data
criteria.  It also fixes some issues with the use of the generic patient
characteristic.  If the generic patient characteristic is used for
birthdate or gender, we convert it to the properly typed characteristic.  I
believe that all cases of the use of the generic characteristics in the
measure defs have been resolved... So in reality all its doing at this
point is embedding the value for gender into the value field of the data
criteria for use in calculation.

**Comment by marks** [comment]
OK, so this has to do with details for data criteria but would not cause any data criteria to not be included in the parsed Hash object, correct?

**Comment by andrequina** [comment]
Correct.  You will still get all the data criteria.

**Comment by marks** [comment]
Thank you - I believe this addresses all my questions so I am closing this issue thread
