### ISSUE TITLE
Does this repo (projectcypress/health-data-standards) effectively replace pophealth/hqmf-parser?

### ISSUE THREAD

**Issue by marks** [MeasureAuthoringTool/health-data-standards#42]
I see that [pophealth/hqmf-parser](https://github.com/pophealth/hqmf-parser) has not been worked on as recently as [the relevant files in this project](https://github.com/projectcypress/health-data-standards/tree/master/lib/hqmf-parser).

Accordingly, if HQMF R1/R2 parsing is needed, should this repository be used rather than pophealth/hqmf-parser?

Thank you!

**Comment by hadleynet** [comment]
Use health-data-standards. The code in hqmf-parser was integrated into
health-data-standards some time ago and all ongoing work is happening in
the latter.

Marc.

**Comment by marks** [comment]
Thank you for clarifying. I'd suggest putting a message on pophealth/hqmf-parser for others' benefit.
