### ISSUE TITLE
bundle-latest.zip no longer exists on the new demo server

### ISSUE THREAD

**Issue by frank-west-iii** [MeasureAuthoringTool/health-data-standards#426]
The code here defaults to a file that does not exist on the new demo server.

``` ruby
bundle_version = ENV["version"] || "latest"
```

https://github.com/projectcypress/health-data-standards/blob/04efeebbc9b99d6d8d7a917ff85f1a4ba225fed6/lib/health-data-standards/tasks/bundle.rake#L48

This is a 404 now.

https://cypressdemo.healthit.gov/measure_bundles/bundle-latest.zip

On the previous demo server this behavior worked as expected.

I am not sure what the expected behavior should be. The file should exist or the version should be required?

**Comment by okeefm** [comment]
Hello @frank-west-iii; 

This is on our list to remedy. Because we no longer have a "latest" bundle, but rather have separate bundles for the 2015 and 2016 measures, we will be requiring the `VERSION` environment variable going forward.

**Comment by frank-west-iii** [comment]
@okeefm, unless there are any intricacies, I could simply swap that out with a `ENV.fetch` and a message if not defined when running the task and create a PR?

**Comment by okeefm** [comment]
Yeah, that should solve it.
