### ISSUE TITLE
HQMF parsing: possible to list data elements by location?

### ISSUE THREAD

**Issue by marks** [MeasureAuthoringTool/health-data-standards#48]
I'm wondering what the LOE/suggested course of implementing the following feature/output: I have a need to take a HQMF document, parse it, and, for each data element, see where in the `population_criteria` it exists (`IPP`, `DENEX`, `NUMER`, `DENEXCEP`, etc.). I know many data elements get used several times per measure.

Any guidance is much appreciated!

Thanks,

Mark

**Comment by hadleynet** [comment]
Most of the code you need is already there. The HQMF parser component of health-data-standards will parse the HQMF XML into a data structure that can be traversed to glean the information you are looking for. E.g. measure 0004 has the following structure for the IPP once parsed:

``` json
  "population_criteria": {
    "IPP": {
      "conjunction?": true,
      "type": "IPP",
      "title": "Initial Patient Population",
      "hqmf_id": "8123A2A6-2B21-4865-825A-FA0FA44A56F2",
      "preconditions": [
        {
          "id": 95,
          "preconditions": [
            {
              "id": 72,
              "reference": "OccurrenceAAlcoholAndDrugDependence1_precondition_71",
              "conjunction_code": "allTrue"
            },
            {
              "id": 74,
              "reference": "PatientCharacteristicBirthdateBirthDate_precondition_74"
            },
            {
              "id": 93,
              "reference": "OccurrenceAAlcoholAndDrugDependence1_precondition_93"
            }
          ],
          "conjunction_code": "allTrue"
        }
      ]
    },
    ...
  }
```

This shows that the data criteria "OccurrenceAAlcoholAndDrugDependence1_precondition_71", "PatientCharacteristicBirthdateBirthDate_precondition_74" and ""OccurrenceAAlcoholAndDrugDependence1_precondition_93" are all used in the IPP. You can then look up each of those data criteria to find out more information about them, e.g.:

``` json
  "data_criteria": {
    "OccurrenceAAlcoholAndDrugDependence1_precondition_71": {
      "title": "Alcohol and Drug Dependence",
      "description": "Diagnosis, Active: Alcohol and Drug Dependence",
      "standard_category": "diagnosis_condition_problem",
      "qds_data_type": "diagnosis_active",
      "code_list_id": "2.16.840.1.113883.3.464.1003.106.12.1001",
      "type": "conditions",
      "definition": "diagnosis",
      "status": "active",
      "hard_status": false,
      "negation": false,
      "specific_occurrence": "A",
      "specific_occurrence_const": "DIAGNOSIS_ACTIVE_ALCOHOL_AND_DRUG_DEPENDENCE",
      "source_data_criteria": "OccurrenceAAlcoholAndDrugDependence1",
      "temporal_references": [
        {
          "type": "SAS",
          "reference": "MeasurePeriod",
          "range": {
            "type": "IVL_PQ",
            "high": {
              "type": "PQ",
              "unit": "mo",
              "value": "11",
              "inclusive?": true,
              "derived?": false
            }
          }
        }
      ],
      "subset_operators": [
        {
          "type": "FIRST"
        }
      ]
    },
    ...
  }
```

**Comment by marks** [comment]
@hadleynet Thanks for the quick reply. I had been using this approach but issues arose in traversing nested data elements and temporal references which exist inside a data element. Let me give you an example:

HQMF XML from https://ushik.ahrq.gov/rest/meaningfulUse/retrieveHQMFXML?MeasureId=100&format=hqmf&version=2 (CMS100v2) returns https://gist.github.com/marks/6319696 once parsed.

I want to list the population criteria (IPP, NUMER, etc.) which data element "Medication, Order not done: Medical Reason" (aka "MedicationOrderNotDoneMedicalReason") live in, _however_ I do not see that reference ID in the `population_criteria` hash. 

While I have you, can you explain the difference, if any, between `source_data_criteria` and `data_criteria` root elements and attributes within each other?

Thank you again

**Comment by hadleynet** [comment]
What you are observing is an artifact of the way we normalize the complex HQMF representation. That particular data criteria is rewritten as either MedicationOrderHospitalMeasuresAspirin_precondition_11 or MedicationOrderHospitalMeasuresAspirin_precondition_13 (need to look at the negation code list to determine whether its the patient reason or medical reason), notice the negation=true that corresponds to the "Not Done".

Source data criteria are derived from the data criteria section of the source HQMF. Data criteria are derived from the source data criteria plus the addition restrictions (SBS, FIRST, etc) that are placed on those criteria within the population definition. We restructure the measure so the population contains only the logical operations (AND, OR etc) and other restrictions like temporal operators (SBS, DURING, ...) and subset operators (FIRST, LAST, ...) are push onto the data criteria.
