### ISSUE TITLE
Medication importer with Reason Underweight issue for measure CMS69 (CAT1)

### ISSUE THREAD

**Issue by chelope** [MeasureAuthoringTool/health-data-standards#538]
I have an issue with a patient that should meet numerator for measure CMS69

![cms65numerator](https://user-images.githubusercontent.com/2678164/30039130-95a42976-9192-11e7-84b7-b63700c3279c.png)

The patient has a Medication, Order: Below Normal Medications with Reason Underweight. (CAT1 file)

            
            <substanceAdministration classCode="SBADM" moodCode="RQO">
              <templateId extension="2014-06-09" root="2.16.840.1.113883.10.20.22.4.42"/>
              
              <templateId extension="2016-02-01" root="2.16.840.1.113883.10.20.24.3.47"/>
              <id extension="Get Well Clinic-1-1372-2400-DF" root="2.16.840.1.113883.3.1452.3"/>
              <text>SIG information not entered</text>
              <statusCode code="completed"/>
              <effectiveTime xsi:type="IVL_TS">
                <low value="20170510235959"/>
                <high nullFlavor="UNK"/>
              </effectiveTime>
              <routeCode/>
              <doseQuantity nullFlavor="NA"/>
              <consumable>
                <manufacturedProduct classCode="MANU">
                  
                  <templateId extension="2014-06-09" root="2.16.840.1.113883.10.20.22.4.23"/>
                  <id root="ba86866c-73ff-40cf-841d-26cfe8747a8f"/>
                  <manufacturedMaterial>
                    <code code="860221" codeSystem="2.16.840.1.113883.6.88" codeSystemName="RxNorm" sdtc:valueSet="2.16.840.1.113883.3.600.1.1499" xsi:type="CE">
                      <originalText>SIG information not entered</originalText>
                    </code>
                  </manufacturedMaterial>
                </manufacturedProduct>
              </consumable>
              <author>
                <templateId root="2.16.840.1.113883.10.20.22.4.119"/>
                <time value="20170510235959"/>
                <assignedAuthor>
                  <id root="3fd83a53-d600-4fb6-99c6-60939e63e91e"/>
                </assignedAuthor>
              </author>
              
              <entryRelationship typeCode="RSON">
                <observation classCode="OBS" moodCode="EVN">
                  <templateId extension="2014-12-01" root="2.16.840.1.113883.10.20.24.3.88"/>
                  <id extension="7368fe92-7891-4b76-b65e-524c9ed59668" root="2.16.840.1.113883.3.1452.1011"/>
                  <code code="77301-0" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="reason"/>
                  <statusCode code="completed"/>
                  <effectiveTime>
                    <low value="20170510235959"/>
                  </effectiveTime>
                  <value code="248342006" codeSystem="2.16.840.1.113883.6.96" sdtc:valueSet="2.16.840.1.113883.3.600.2388" xsi:type="CD"/>
                </observation>
              </entryRelationship>
            </substanceAdministration>
          </entry>
          <entry>

I reviewed the class medication_importer.rb (health-data-standards/lib/health-data-standards/import/cda/medication_importer.rb)  the method in charge of to extract the reason or negation is implemented the following way:
        
        def extract_reason_or_negation(parent_element, medication)
          negation_indicator = parent_element['negationInd']
          if negation_indicator.nil? && parent_element.parent.name == "entryRelationship"
            super(parent_element.parent.parent, medication, parent_element)
          elsif negation_indicator.eql?('true')
            super(parent_element, medication)
          end
        end
In my scenario the medication order doesn't have a negationInd=true and  the parent_element.parent.name != "entryRelationship", when the method receives the medication order entry the method doesn't extract the reason. 

I think, the issue could be solved if the method is changed of the following way:

        def extract_reason_or_negation(parent_element, medication)
          negation_indicator = parent_element['negationInd']
          if negation_indicator.nil? && parent_element.parent.name == "entryRelationship"
            super(parent_element.parent.parent, medication, parent_element)
          else
            super(parent_element, medication)
          end
        end

Please let me know if this is an issue or there is something wrong in my medication order entry.

Thanks in advance.

**Comment by dczulada** [comment]
Thanks for pointing this out.  This has been addressed in the most recent releases of Health Data Standards (3.7.0 and 4.1).
