### ISSUE TITLE
Any relation to 2015 CEHRT?

### ISSUE THREAD

**Issue by runvnc** [MeasureAuthoringTool/health-data-standards#561]
Hello, sorry if this question is too basic, but does this software implement any portion of the 2015 CEHRT, or does it actually relate to that in any way?

**Comment by dillonwelch** [comment]
I don't think so

**Comment by dczulada** [comment]
The Health Data Standards library is used by the Cypress application which is used to perform the 170.315(c)(1) - 170.315(c)(4) Certification Criteria.
