### ISSUE TITLE
Basic use documentation

### ISSUE THREAD

**Issue by Mysrt** [MeasureAuthoringTool/health-data-standards#585]
Found this gem when trying to investigate CDA parsing options outside of pure nokogiri.  This gem seems very useful but there seems to be no documentation or examples anywhere on how to use it.  Producing some documentation would be helpful.

**Comment by okeefm** [comment]
@Mysrt more documentation is definitely a good idea. We're looking into some better basic documentation. In the meantime, let us know if you have any specific usage questions; we'd be happy to answer them.
