### ISSUE TITLE
Citation(s)

### ISSUE THREAD

**Issue by hrieke** [MeasureAuthoringTool/health-data-standards#587]
Hi guys,

You also use a few xsd file from Health Level 7 which are listed under the BSD 3 clause license; could you please give a proper citation for those files?
https://www.w3.org/2005/05/25-schema/HL7.html
http://www.hl7.org/implement/standards/product_brief.cfm?product_id=214

Thanks

**Comment by okeefm** [comment]
@hrieke Thanks for bringing this to our attention! We'll add in citations for those files.
