### ISSUE TITLE
health-data-standards on https://rubygems.org

### ISSUE THREAD

**Issue by wahmedswl** [MeasureAuthoringTool/health-data-standards#638]
Hi,
From which branch gem is being published on https://rubygems.org as ```master``` is stalled and most of the activity is on ```bonnie-gemfile-update```, ```master_bonnie```, ```activesupport``` and ```update_nokogiri```.

Thanks

**Comment by mayerm94** [comment]
Hi,

The health-data-standards v4.3.5 gem was published using the code from the v4.3.5 tagged commit https://github.com/projectcypress/health-data-standards/tree/v4.3.5. The v4.3.5 tagged commit is also currently the most recent commit in the ‘master_bonnie’ branch.

Thanks,
Matt
