### ISSUE TITLE
representedCustodianOrganization

### ISSUE THREAD

**Issue by yoon** [MeasureAuthoringTool/health-data-standards#82]
https://github.com/projectcypress/health-data-standards/blob/10dac4c594216493e7fb014a61b061061caff985/templates/cat3/_organization.cat3.erb#L1

In our instance, the cat3 template header somehow always outputs a representedOrganization tag, although by all review of the code, setting a local variable on the partial should change the tag to representedCustodianOrganization.

See: https://github.com/projectcypress/health-data-standards/commit/10dac4c594216493e7fb014a61b061061caff985#diff-dac787bbb748f453b53a9a5b3abde5edL1

**Comment by eedrummer** [comment]
Fixed and tested by #132
